### ISSUE TITLE
Please add a screen shot and README

### ISSUE THREAD

**Issue by unixorn** [davidparsson/zsh-dp-theme#1]
I'd like to add this to the themes index in [awesome-zsh-plugins](https://github.com/unixorn/awesome-zsh-plugins), but prefer to add themes that have screen shots so that users can tell what they are going to look like.

**Comment by unixorn** [comment]
Cool, adding to [awesome-zsh-plugins](https://github.com/unixorn/awesome-zsh-plugins) as of [awesome-zsh-plugins/pull/317](https://github.com/unixorn/awesome-zsh-plugins/pull/317)

**Comment by davidparsson** [comment]
🕺
